[api] update descriptions of the radio platform power APIs
openthread/openthread pull request #10839
Opened 2024-10-15 06:09 UTC by zhanglongxia

Current radio platform defines three power related APIs: `otPlatRadioSetTransmitPower()`, `otPlatRadioSetChannelMaxTransmitPower()` and `otPlatRadioSetChannelTargetPower()`. However, the descriptions of these APIs do not clearly define the relationship between them, which causes a lot of confusion for radio platform developers.

https://github.com/orgs/openthread/discussions/10761 https://github.com/orgs/openthread/discussions/10611 https://github.com/orgs/openthread/discussions/9899

This commit updates the descriptions these APIs to clearly define the relationship between these power APIs.

2024-10-15 20:06 UTC, abtink approved these changes
Thanks. 👍

2024-10-15 23:03 UTC, bukepo approved these changes

2024-10-16 03:21 UTC, bukepo approved these changes

2024-10-17 17:23 UTC, Vyrastas requested changes
Two minor nits

2024-10-17 17:23 UTC, Vyrastas commented on include/openthread/platform/radio.h
> + * the current channel that configured by `otPlatRadioSetChannelMaxTransmitPower()`.
```suggestion
 * the current channel that was configured by `otPlatRadioSetChannelMaxTransmitPower()`.
```

2024-10-17 17:23 UTC, Vyrastas commented on include/openthread/platform/radio.h
> + *       - If neither of these two functions is called, the radio outputs the platform defined default power.
```suggestion
 *       - If neither of these two functions is called, the radio outputs the platform-defined default power.
```

2024-10-21 19:48 UTC, Vyrastas approved these changes

2024-10-21 21:50 UTC, jwhui approved these changes

2024-10-21 21:50 UTC, merged