[border-agent] update docs for set and clear ephemeral key APIs
openthread/openthread pull request #10854
Opened 2024-10-21 07:56 UTC by sunytt

The docs are updated to mention that users can use the `otBorderAgentDisconnect()` API to forcely disconnect from commissioner sessions.

2024-10-21 12:41 UTC, Irving-cl approved these changes
LGTM 👍

2024-10-22 04:45 UTC, abtink approved these changes
👍

2024-10-22 05:47 UTC, librasungirl approved these changes

2024-10-22 19:00 UTC, Vyrastas requested changes
Just some minor suggestions for switching the word order

"use the XY API/function"

(instead of "use the API/function XY")

2024-10-22 19:00 UTC, Vyrastas commented on include/openthread/border_agent.h
> + * To terminate active commissioner sessions, use the API `otBorderAgentDisconnect()`.
```suggestion
 * To terminate active commissioner sessions, use the `otBorderAgentDisconnect()` API.
```

2024-10-22 19:00 UTC, Vyrastas commented on include/openthread/border_agent.h
> + * API `otBorderAgentDisconnect()`.
```suggestion
 * `otBorderAgentDisconnect()` API.
```

2024-10-22 19:00 UTC, Vyrastas commented on src/core/meshcop/border_agent.hpp
> +     * use the function `Disconnect()`.
```suggestion
     * use the `Disconnect()` function.
```

2024-10-22 19:00 UTC, Vyrastas commented on src/core/meshcop/border_agent.hpp
> +     * function `Disconnect()`.
```suggestion
     * `Disconnect()` function.
```

2024-10-23 00:55 UTC, sunytt commented on include/openthread/border_agent.h
> + * To terminate active commissioner sessions, use the API `otBorderAgentDisconnect()`.
Thanks, done.

2024-10-23 01:57 UTC, Vyrastas approved these changes

2024-10-23 12:11 UTC, merged