[efr32] Update for compatibility with GSDK 3.0
openthread/openthread pull request #5529
Opened 2020-09-14 20:13 UTC by lmnotran

This PR includes a relatively minimal set of changes that are required to allow the efr32 platforms to function with the newly released Silabs Gecko SDK v3.0. 

# Change Log

- Pull in definitions for `halInitChipSpecific()` and all child functions from GSDK v2.7.
  - These will be replaced with a more elegant solution in a future PR.
- Switch to the mbedtls that is packaged with GSDK v3.0.
- Allow for mixed casing when specifying `BOARD` environment variable

2020-09-16 16:06 UTC, lmnotran commented on examples/platforms/efr32mg13/system.c
> -#include "openthread-core-efr32-config.h"
This is included in `#include <openthread-core-config.h>	`

2020-09-16 17:15 UTC, romacdon requested changes

2020-09-16 20:41 UTC, romacdon approved these changes

2020-09-16 20:42 UTC, romacdon commented
@jwhui I approved this PR but I would like @schinchani to review as well too but I can seem to assign him as a reviewer.

2020-09-16 20:44 UTC, jwhui commented
> @jwhui I approved this PR but I would like @schinchani to review as well too but I can seem to assign him as a reviewer.

@romacdon , I updated @schinchani 's config. Can you try again?

2020-09-16 20:51 UTC, romacdon commented
> > @jwhui I approved this PR but I would like @schinchani to review as well too but I can seem to assign him as a reviewer.
> 
> @romacdon , I updated @schinchani 's config. Can you try again?

Thanks for the unbelievably speedy reply!  I was able to add him as a reviewer.  Can ask what config you needed to change in case I need to something similar for other reviewers in the future?

2020-09-16 21:21 UTC, jwhui commented
> Thanks for the unbelievably speedy reply! I was able to add him as a reviewer. Can ask what config you needed to change in case I need to something similar for other reviewers in the future?

@romacdon , I needed to add him to the `openthread/silicon-labs` group on GitHub.

2020-09-17 09:15 UTC, romacdon approved these changes

2020-09-17 12:56 UTC, schinchani approved these changes
Looks good to me @lmnotran

2020-09-17 14:48 UTC, merged