[unit] add a README guide for unit tests
openthread/openthread pull request #8791
Opened 2023-02-22 10:29 UTC by Irving-cl

This PR adds a README about building and running unit tests.

2023-02-22 10:58 UTC, wgtdkp approved these changes
Very useful documentation :+1:

2023-02-22 19:24 UTC, abtink commented on tests/unit/README.md
> +## Build Simulation
This is useful. Thanks @Irving-cl .

I usually use this one command `./tests/toranj/build.sh cmake`  
- This sets up and builds everything (cli/ncp ftd/mtd/rcp) and all the unit tests. 
- Afterwards can use `ninja` from the openthread root folder to re-build (if there is any change).
- What I like about this is that unit test executable will be in the same folder as the source files (can run like `./tests/unit/ot-test-message`)

2023-02-22 19:24 UTC, abtink approved these changes

2023-02-23 01:02 UTC, superwhd approved these changes
LGTM :+1:

2023-02-23 20:38 UTC, Vyrastas requested changes

2023-02-23 20:38 UTC, Vyrastas commented on tests/unit/README.md
> +This page shows how to build and run OpenThread unit tests. It will be helpful for developers to debug failed unit test cases if they got one in CI or to add some new test cases.
This page describes

2023-02-23 20:38 UTC, Vyrastas commented on tests/unit/README.md
> +The unit tests cannot be built solely without building the whole project. So first build OpenThread on simulation platform:
on the simulation platform, which will also build all unit tests:

2023-02-23 20:38 UTC, Vyrastas commented on tests/unit/README.md
> +Now all the unit tests should have been built.
Delete this since it'll be mentioned above.

2023-02-23 20:38 UTC, Vyrastas commented on tests/unit/README.md
> +To see what tests are there in OpenThread:
are available in OpenThread:

2023-02-23 20:38 UTC, Vyrastas commented on tests/unit/README.md
> +./script/cmake-build simulation
I would use $ before each command so it's clear, and to be consistent with our other documentation

2023-02-23 20:38 UTC, Vyrastas commented on tests/unit/README.md
> +ctest -N
As mentioned earlier, add the terminal prompt for this command and any others below 

`$ ctest -N`

2023-02-23 20:38 UTC, Vyrastas commented on tests/unit/README.md
> +## Update A Test Case
A should be lowercase ---> a

2023-02-23 20:38 UTC, Vyrastas commented on tests/unit/README.md
> +For example, we are developing a unit test case. We made some changes in the test source file and want to run the updated executable. We can run:
If you are developing a unit test case and have made some changes in the test source file, you will need rebuild the test before running it:

2023-02-23 20:38 UTC, Vyrastas commented on tests/unit/README.md
> +If we found there are some errors in OpenThread code and we made some fixes, then we need to build the whole project. Simply run:
If any changes or fixes were made to the OpenThread code, then you'll need to rebuild the entire project:

2023-02-24 16:54 UTC, Vyrastas approved these changes
One misspelling to fix

2023-02-24 16:54 UTC, Vyrastas commented on tests/unit/README.md
> +The unit tests cannot be built solely without building the whole project. So first build OpenThread on the simulation platform, whilc will also build all unit tests:
whilc --> which

2023-02-27 17:02 UTC, merged