Added CLI command documentation for rcp and route.
openthread/openthread pull request #8800
Opened 2023-02-23 23:24 UTC by kylorene

Updated RCP command documentation in CLI.

Merged RCP CLI commands in documentation.

Updated region and route CLI.

Updated region and route.

Updated route.

Updated route add.

Updated parameters for route add.

Added parameters for router.

Added formatting for parameters.

Updated route command function.

Updated rcp version parameter.

2023-02-23 23:28 UTC, Vyrastas commented on src/cli/cli.cpp
> +{
Looks like this bracket got moved and is causing all the failures.  It should be on line 6264 (between template and return).

2023-02-24 16:51 UTC, Vyrastas requested changes
The actual comments seem fine, just some formatting issues to address to keep it consistent with everything that's already there.  Make sure to run the import to DevSite again after you make these changes to verify it's still good on that side.

2023-02-24 16:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Move this block left to align with the "template" on line 6216

2023-02-24 16:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Move this between 6261 and 6262 (between #if and template), and move left to align with "template"

2023-02-24 16:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Move left to align with "template"

2023-02-24 16:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Move this above the "template" (line 6556) and move left to align with that

2023-02-24 16:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +         */
Move left to align with "else" on line 6611

2023-02-24 16:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Move before the "template" (line 6624) and move left to align with it

2023-02-24 16:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Move before the "template" (line 6646) and move left to align with it

2023-02-24 16:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Move before the "template" (line 6668) and move left to align with it

2023-02-24 16:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +
Remove this blank line... try not to add/remove blank lines that already exist in the file, whatever is already there should be left as is

2023-02-24 19:16 UTC, Vyrastas requested changes
The formatting fixes reverted some of the recent changes you did before submitting the PR.  I've commented on them... please fix and re-run the reference import so we can validate again.

2023-02-24 19:16 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Still not left-aligned to template

2023-02-24 19:16 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Still not left-aligned to template

2023-02-24 19:16 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Still not left-aligned to template

2023-02-24 19:16 UTC, Vyrastas commented on src/cli/cli.cpp
> +     */
Still not left-aligned to template

2023-02-24 19:16 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * #otThreadGetRouterInfo
These 2 lines are supposed to be

```
* @sa otThreadGetRouterInfo
```

2023-02-24 19:16 UTC, Vyrastas commented on src/cli/cli.cpp
> -     * @cparam router [@ca{id}]
Add this line back

2023-02-24 19:16 UTC, Vyrastas commented on src/cli/cli.cpp
> -     * @cparam route remove [@ca{prefix}]
Add this line back

2023-02-24 23:50 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * Print RCP version string.
This one still needs doing

2023-02-24 23:50 UTC, Vyrastas commented on src/cli/cli.cpp
> + * @cli region
Can you move this block down before the current line 6234

```
if (aArgs[0].IsEmpty())
```

2023-02-24 23:51 UTC, Vyrastas commented on src/cli/cli.cpp
> +    /**
Can you move this block down before the current line 6239 (the `else` block)

2023-02-27 17:02 UTC, Vyrastas commented on src/cli/cli.cpp
> + * #otPlatRadioGetRegion
This is duplicated (it's already before the template line).  Please remove

2023-02-27 21:31 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * #otThreadIsRouterEligible
This should be 

#otThreadSetRouterEligible

2023-02-27 21:32 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * #otThreadIsRouterEligible
These two lines:

```
* @par api_copy
* #otThreadIsRouterEligible
```

Should be just an sa

```
* @sa otThreadIsRouterEligible
```

2023-02-27 21:34 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * #otThreadIsRouterEligible
These two lines

```
* @par api_copy
* #otThreadIsRouterEligible
```

Should be 

```
* @sa otThreadSetRouterEligible
```

2023-02-27 21:34 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * #otThreadIsRouterEligible
These two lines

```
* @par api_copy
* #otThreadIsRouterEligible
```

Should be 

```
* @sa otThreadSetRouterEligible
```

2023-02-28 06:50 UTC, Vyrastas commented
Just need to run make pretty and this should be good

2023-02-28 19:11 UTC, jwhui approved these changes

2023-02-28 19:11 UTC, merged