[dnssd] Add API for getting the upstream query status.
openthread/openthread pull request #8815
Opened 2023-02-28 09:41 UTC by erjiaqing

Adds a new API for getting the state of DNS query forwarder.

2023-02-28 18:59 UTC, abtink approved these changes
LGTM. 👍

2023-03-01 11:37 UTC, Irving-cl approved these changes
LGTM 👍

2023-03-01 21:03 UTC, Vyrastas requested changes

2023-03-02 04:44 UTC, erjiaqing commented on include/openthread/dnssd_server.h
> + * This function indicates whether the DNSSD server will forward DNS queries to platform DNS upstream API.
done

2023-03-02 04:58 UTC, Vyrastas approved these changes

2023-03-02 06:42 UTC, jwhui approved these changes

2023-03-02 06:42 UTC, merged