Network partition
openthread/openthread pull request #8875
Opened 2023-03-16 20:27 UTC by kylorene

2023-03-20 22:35 UTC, Vyrastas requested changes

2023-03-20 22:35 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * #otThreadGetPartitionId
Switch the api_copy to an `@sa` here

2023-03-20 22:35 UTC, Vyrastas commented on src/cli/cli.cpp
> +     *@sa otThreadSetPreferredLeaderPartitionId
This imported okay, but for readability need a space between `*` and `@sa`

2023-03-20 22:35 UTC, Vyrastas commented on src/cli/cli.cpp
> +  * @sa otPingSenderPing
Needs to move left one space

2023-03-21 16:34 UTC, Vyrastas requested changes

2023-03-21 16:34 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * @cli partitionid preferred (partitionid) (get,set)
Let's remove the (partitionid) from the name

`* @cli partitionid preferred (get,set)`

2023-03-21 16:34 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * Note: OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE is required.
This doesn't need to be a note for our docs, but put the flag in code font

`OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE` is required.

2023-03-21 16:34 UTC, Vyrastas commented on src/cli/cli.cpp
> + * @cli pollperiod (pollperiod)
`* @cli pollperiod (get,set)`

2023-03-21 17:28 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * 'OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE' is required.
Make it backticks around OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE  so it's code font

2023-03-23 23:49 UTC, Vyrastas approved these changes
Please rebase/squash

2023-03-25 04:42 UTC, jwhui approved these changes

2023-03-25 04:42 UTC, merged