[net-diag] add TLV for MLE counters
openthread/openthread pull request #9024
Opened 2023-05-04 23:52 UTC by abtink

This commit introduces Network Diagnostic TLV for MLE counters.
It updates `NetworkDiagnostic::Server` to provide this TLV when
queried and provide support for retrieving on `Client`.

----

This PR contains the commit from https://github.com/openthread/openthread/pull/8866

2023-05-08 21:04 UTC, Vyrastas requested changes

2023-05-08 21:04 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * meshdiag childrenip6addr 0xdc00
childrenip6addr --> childip6

2023-05-08 21:04 UTC, Vyrastas commented on src/cli/cli.cpp
> +     *     csl - sync:no period:0 timeout:0 channel:0
Need `Done` at the end?

2023-05-08 21:04 UTC, Vyrastas commented on src/cli/cli.cpp
> +     *     fd00:1:0:0:1fcf:5495:790a:370f
Need `Done` at the end?

2023-05-08 21:04 UTC, Vyrastas commented on src/cli/cli.cpp
> +     *    err-rate - frame:0.72% msg:0.00%
Need `Done` at the end?

2023-05-08 21:04 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * * CSL info
colon at end

CSL info:

2023-05-09 22:38 UTC, abtink commented
Thanks @Vyrastas. I added the suggestions above in https://github.com/openthread/openthread/pull/8866#issuecomment-1540973549 (which is the main PR adding "Child TLV and Neighbor TLV" for Network Diagnostic, etc).

This PR is for MLE Counters TLV (but I added it on top of the commit from the other PR to avoid conflict when we merge them). I may later include this in #8866 and close this PR.

2023-05-18 00:18 UTC, abtink commented
I include the commit in this PR into https://github.com/openthread/openthread/pull/8866. So we can close this.

2023-05-18 00:18 UTC, closed without merging