[docs] cli cmd doc updates (mliid - multiradio neighbor)
openthread/openthread pull request #9155
Opened 2023-06-07 22:40 UTC by gavinmcgovern

2023-06-08 19:16 UTC, Vyrastas requested changes

2023-06-08 19:16 UTC, Vyrastas commented on src/cli/cli.cpp
> + * #otMultiRadioGetNeighborInfo
We shouldn't link this API here, it's for the neighbor info that requires OPENTHREAD_CONFIG_MULTI_RADIO

2023-06-08 21:58 UTC, Vyrastas approved these changes
I think you need to bump up the API version again and then squash to get it all into 1 commit

2023-06-09 22:52 UTC, jwhui approved these changes

2023-06-09 22:52 UTC, merged