[mle] update `otThreadBecomeLeader()` to allow leader take over
openthread/openthread pull request #9186
Opened 2023-06-15 16:12 UTC by abtink

This commit updates the `otThreadBecomeLeader()` API (and its related core `MleRouter::BecomeLeader()` method) to allow an already attached device to take over as leader, creating a new partition. For this to work, the local leader weight (`otThreadGetLocalLeaderWeight()`) must be greater than the weight of the current leader (which can be retrieved using `otThreadGetLeaderWeight()`). If it is not, error code `OT_ERROR_NOT_CAPABLE` is returned to indicate to the caller that they need to adjust the local weight.

This commit also updates the related CLI command and adds a new test, `test-031-leader-take-over.py`, to validate the newly added mechanism.

----

Related to [SPEC-1140](https://threadgroup.atlassian.net/browse/SPEC-1140).

2023-06-21 10:12 UTC, EskoDijk commented on src/cli/README.md
> +If the device is already attached, this API can be used to try to take over as the leader, creating a new partition. For this to work, the local leader weight (`leaderweight`) must be larger than the
To add similar disclaimer here that doing this without explicit user action can make device non-compliant.

2023-06-21 10:22 UTC, EskoDijk requested changes
Code looks okay, some more disclaimers on the documentation and comments would be needed for the case of leader takeover while connected.

2023-06-21 16:56 UTC, abtink commented on include/openthread/thread_ftd.h
>   *
Added in new push.

2023-08-08 09:23 UTC, EskoDijk approved these changes
I rechecked the latest code; and all looks ok to me.

2024-07-12 18:34 UTC, nand-nor commented
@abtink @EskoDijk any plans to merge this in?

2024-07-12 20:56 UTC, abtink commented
> @abtink @EskoDijk any plans to merge this in?

I am okay merging this. Just rebased it on `main`.

2024-07-17 23:45 UTC, Vyrastas approved these changes

2024-07-18 02:43 UTC, jwhui approved these changes

2024-07-18 02:43 UTC, merged

2024-07-18 02:43 UTC, jwhui commented
> @abtink @EskoDijk any plans to merge this in?

@nand-nor , merged!