[mle] suppress Announce response to orphan child on same channel and PAN ID
openthread/openthread pull request #9388
Opened 2023-08-30 20:24 UTC by abtink

This commit updates MLE to skip sending an Announce response when receiving an Announce message from a detached/orphan device and the included channel and PAN ID in the received Announce message are the same as the current network's channel and PAN ID.

---

Related to [SPEC-1165](https://threadgroup.atlassian.net/browse/SPEC-1165).

2023-09-01 10:40 UTC, EskoDijk requested changes
This looks good; as it avoids sending announce triggered by devices that are on the same PANID and channel.

I was wondering where the code is that will use a mAlternateChannel/PanId from a received announce to do some attach attempt(s) with? Could not find it easily.

2023-09-01 10:40 UTC, EskoDijk commented on src/core/thread/mle.cpp
> +    bool                      isFromOrhpan;
```suggestion
    bool                      isFromOrphan;
```

2023-09-01 14:08 UTC, abtink commented on src/core/thread/mle.cpp
> +    bool                      isFromOrhpan;
Thanks. Fixed it in new push

2023-09-01 14:25 UTC, abtink commented
> I was wondering where the code is that will use a mAlternateChannel/PanId from a received announce to do some attach attempt(s) with? Could not find it easily.

@EskoDijk , I think you mean this part:
https://github.com/openthread/openthread/blob/830572f81680ceb29524e215487709d3e6217121/src/core/thread/mle.cpp#L3744-L3757

which uses `mAttachTimer` to add delay before processing it from timer callback:
https://github.com/openthread/openthread/blob/830572f81680ceb29524e215487709d3e6217121/src/core/thread/mle.cpp#L1472-L1474

which then calls:

https://github.com/openthread/openthread/blob/830572f81680ceb29524e215487709d3e6217121/src/core/thread/mle.cpp#L3840-L3860

2023-09-05 11:50 UTC, EskoDijk commented
@abtink Yes, this was the code I was looking for; thanks. Looks good now with the update.

2023-09-05 11:50 UTC, EskoDijk approved these changes

2023-09-11 13:48 UTC, jwhui approved these changes

2023-09-11 13:49 UTC, merged