CLI updates
openthread/openthread pull request #9401
Opened 2023-09-05 16:49 UTC by jrhodie

2023-09-05 18:57 UTC, abtink approved these changes
LGTM. 👍

2023-09-05 19:07 UTC, Vyrastas requested changes
Looks really good, just a few things

2023-09-05 19:07 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * - SNTP server default port: 123
port value should be code font

`123`

2023-09-05 19:07 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * Returns the current role of the Thread device, or changes the role as specified with one of the  options.
double space between the and options

2023-09-05 19:07 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * changing to or from `disabled` state.
to or from a `disabled` state

2023-09-06 00:00 UTC, Vyrastas requested changes

2023-09-06 00:00 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * Returns the current role of the Thread device, or changes the role as specified with one of the  options.
Double space still there

2023-09-06 00:00 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * Using one of the options allows you to change the current role of a device, with the excluson of
excluson --> exclusion

2023-09-06 15:45 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * Returns the current role of the Thread device, or changes the role as specified with one of the  options.
Double space still there!

`the  options` --> `the options`

2023-09-06 18:19 UTC, Vyrastas approved these changes

2023-09-06 20:53 UTC, jwhui approved these changes

2023-09-06 20:53 UTC, merged