Added Doxygen tags to all "trel" commands.
openthread/openthread pull request #9406
Opened 2023-09-07 02:08 UTC by jrhodie

2023-09-07 14:32 UTC, abtink reviewed
Looks good. Two small suggestions below. Thanks.

2023-09-07 14:32 UTC, abtink commented on src/cli/cli.cpp
> +       |   2 | ce792a29d3111aea | dead00beef00cafe | [fe80:0:0:0:5c57:85ba:3a63:adb9]:9203            |
Add missing `*`?

2023-09-07 14:32 UTC, abtink commented on src/cli/cli.cpp
> +       >>>>>>> [trel] implement new TREL model using DNS-SD
Remove this line?
```suggestion
   
```

2023-09-07 16:19 UTC, Vyrastas requested changes

2023-09-07 16:19 UTC, Vyrastas commented on src/cli/cli.cpp
> + * @sa otTrelIsEnabled
We can do an `@par api_copy` for this one and still keep the `@note`

2023-09-07 19:25 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * @cli trel filter (enable,disable)
Can we move this block down so it's just before the ProcessEnableDisable line?  (similar to how you have the `trel` / `trel (enable,disable)` ones above)

2023-09-07 23:08 UTC, Vyrastas approved these changes

2023-09-08 16:59 UTC, abtink approved these changes
LGTM. Thanks.

2023-09-08 17:02 UTC, jwhui approved these changes

2023-09-08 17:02 UTC, merged