Tvcheck
openthread/openthread pull request #9419
Opened 2023-09-12 18:11 UTC by jrhodie

2023-09-12 19:44 UTC, Vyrastas requested changes

2023-09-12 19:44 UTC, Vyrastas commented on src/cli/cli.cpp
> + * @cli tvcheck(enable,disable)
Need a space after tvcheck

`tvcheck (enable,disable)`

2023-09-12 19:44 UTC, Vyrastas commented on src/cli/cli.cpp
> + * Enables or disables the  thread-version check when upgrading to router or leader.
Thread-version

Also there's a double space between "the" and "thread"

2023-09-12 19:44 UTC, Vyrastas commented on src/cli/cli.cpp
> + * @cli txpower(get,set)
Need a space after txpower

`txpower (get,set)`

2023-09-12 19:44 UTC, Vyrastas commented on src/cli/cli.cpp
> + * @par api_copy
For this one, since it both gets and sets, let's not use the api_copy but instead add a custom description, then do `@sa` for both APIs.

2023-09-12 19:44 UTC, Vyrastas commented on src/cli/cli.cpp
> + * @code
Can you swap the examples so the set is first (so it looks like you're setting it to -10, then getting the -10 back)

2023-09-12 19:44 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * @par api_copy
Let's not use api_copy here.  The API says it returns a pointer while this returns the port number(s), so let's use a custom description instead

2023-09-12 19:44 UTC, Vyrastas commented on src/cli/cli.cpp
> +     * @cparam unsecure add @ca{port}
unsecure --> unsecureport

2023-09-13 15:36 UTC, Vyrastas requested changes
Looks good just one comment

2023-09-13 15:36 UTC, Vyrastas commented on src/cli/cli.cpp
> + * Enables or disables the thread-version check when upgrading to router or leader.
Thread version

(capital T, no hyphen)

2023-09-13 17:21 UTC, abtink approved these changes
LGTM.

2023-09-14 15:50 UTC, jwhui approved these changes

2023-09-14 15:50 UTC, merged