[ccm] Fix discovery response format for CCM networks when non-CCM routers are not allowed
openthread/openthread pull request #9445
Opened 2023-09-20 17:40 UTC by suveshpratapa

For 1.2 certification (specifically _"TC 5.2.4 (DISC-TC-04): 1.1/1.2 non-CCM Joiner does not join CCM Network"_): CCM networks are supposed to include AE port and NMKP port, and NOT include the legacy joiner UDP port, so that the non-CCM router that is trying to join can see the discovery response and not proceed with joining.  AE port / NMKP port, and other CCM concepts are now deprecated in the OpenThread stack.  Still, we need some hooks here to pass certification properly.

1. Don't include joiner UDP port when non-CCM routers are not allowed on the network.
2. Non-CCM joiners should not proceed with joining when joiner UDP port is not included.
3. Separately, we're following up with test harness implementation to fix the scripting for 1.2 certification test "TC 5.2.4 (DISC-TC-04): 1.1/1.2 non-CCM Joiner does not join CCM Network"

2023-09-20 17:40 UTC, suveshpratapa commented
cc @jwhui @abtink @edmont @JaneFromSilabs @romacdon

2023-09-20 18:18 UTC, abtink approved these changes
Thanks. LGTM.

2023-09-21 09:07 UTC, EskoDijk requested changes
see comments!

2023-09-21 13:08 UTC, suveshpratapa commented on src/core/thread/mle_router.cpp
> -    SuccessOrExit(
Thank you, so in the spirit of this change, if a CCM network does not want to allow non-CCM joining as per security policy, we should not include the steering data.  Correct?

2023-09-21 17:02 UTC, abtink commented on src/core/thread/discover_scanner.cpp
> +    VerifyOrExit(joinerUdpPortTlvPresent, error = kErrorDrop);
Good catch @EskoDijk . I did not notice the added check. I agree we should not drop the message if there is no joiner UDP port. 

I would say it should be up to consumer of the discover result to check if what it wants is received.

2023-09-21 17:37 UTC, jwhui commented on src/core/thread/discover_scanner.cpp
> +    VerifyOrExit(joinerUdpPortTlvPresent, error = kErrorDrop);
I agree. The callback should be triggered to provide visibility to the client.

2023-09-26 13:06 UTC, suveshpratapa commented
@EskoDijk and I had a discussion on the Thread Group JIRA where I opened an issue with TC 5.2.4.

TC 5.2.4 is going to be waived / removed from the test specification as it tests for CCM-network capabilities which OpenThread does not provide anymore (AE / NMKP port TLVs etc.).

The spirit of this PR was to ensure that a non-CCM joiner cannot join a CCM network. But we discussed that we can never actually make that decision based on the joiner UDP port. Rather it should depend on whether the steering data allows us to join. The decision to remove or clear the steering data should be made by the commissioner and not if we're a CCM network or not. In this case, it would be the test harness that would make such a decision on the commissioner role -- however this test is going to be removed anyway.

I reduced the scope of this PR to a simple change -- only initiate joining / accept a joiner router if they include a valid (non-zero) joiner UDP port TLV.

cc @jwhui @abtink

2023-09-26 13:06 UTC, suveshpratapa commented on src/core/thread/discover_scanner.cpp
> +    VerifyOrExit(joinerUdpPortTlvPresent, error = kErrorDrop);
Resolving this comment.  See update here: https://github.com/openthread/openthread/pull/9445#issuecomment-1735507159

2023-09-26 13:06 UTC, suveshpratapa commented on src/core/thread/mle_router.cpp
> -    SuccessOrExit(
Resolving this comment. See update here: https://github.com/openthread/openthread/pull/9445#issuecomment-1735507159

2023-09-27 15:31 UTC, EskoDijk commented
@suveshpratapa Agree with the proposed update (single line) in joiner.cpp. As I understand it, the member var `mJoinerUdpPort` will be initialized with `0` when creating a new `ScanResult`. Only when an actual Joiner UDP Port TLV is received, with a >0 value, will the value `mJoinerUdpPort` be set to > 0. So this looks correct. I can't change my review result it seems, but it's Approved.

2023-09-27 16:59 UTC, suveshpratapa commented
Thank you @EskoDijk !

2023-09-27 18:16 UTC, jwhui approved these changes
Thanks! 👍🏼

2023-09-28 13:49 UTC, suveshpratapa commented
Can we merge this now?

2023-09-28 15:24 UTC, merged