[ping-sender] allow setting multicast loop
openthread/openthread pull request #9494
Opened 2023-10-07 17:32 UTC by abtink

This commit updates `PingSender` and its config to include a `mMulticastLoop` flag and allow the caller to set this flag. When set, multicast ping echo request messages are looped back and received by the device itself if it is subscribed to the same address. The `ping` CLI command is also updated to allow setting this flag.

This commit also updates `test-008-multicast-traffic.py` to add new test cases to cover the multicast loop flag behavior (pinging with or without this flag). In particular, it covers when the ping destination is a realm-local multicast address and when it is a larger-than-realm-local multicast address (where the `ot::Ip6` module would use a tunnel header for forwarding the message).

2023-10-10 15:55 UTC, EskoDijk commented on src/cli/README.md
> +- m: multicast loop, which allows looping back pings to multicast addresses that the device itself is subscribed to.
on purpose no hyphen here before the `m` ?

2023-10-10 15:58 UTC, EskoDijk commented on tests/toranj/cli/test-008-multicast-traffic.py
> +# Subscribe to a larger than realm-local scope (sit-local) multicast address on r1, r2, and sed
```suggestion
# Subscribe to a larger than realm-local scope (site-local) multicast address on r1, r2, and sed
```

2023-10-10 15:59 UTC, EskoDijk commented on tests/toranj/cli/test-008-multicast-traffic.py
> +# r3  =>> site-local mcast addr (on r1, r2, sed). Expected to receive from [r1, r2, sed].
```suggestion
# r3  =>> site-local mcast addr (on r1, r2, sed) with `multicast-loop`. Expected to receive from [r1, r2, sed].
```

2023-10-10 16:01 UTC, EskoDijk commented on tests/toranj/cli/test-008-multicast-traffic.py
> +# sed  =>> site-local mcast addr (on r1, r2, sed). Expected to receive from [r1, r2].
add here "without multicast-loop"? (Or is it left out on purpose)

2023-10-10 16:02 UTC, EskoDijk requested changes
Looks useful for testing to have the `-m` flag available. Minor changes proposed

2023-10-11 18:37 UTC, jwhui approved these changes

2023-10-11 18:37 UTC, merged