Reference groups added and typos fixed
openthread/openthread pull request #9709
Opened 2023-12-12 04:51 UTC by jrhodie

2023-12-12 16:28 UTC, Vyrastas requested changes

2023-12-12 16:28 UTC, Vyrastas commented on doc/ot_api_doc.h
> + * @defgroup api-ble-secure           BLE
Let's use "BLE Secure" here since it's specifically for TLS over BLE, not just regular BLE

2023-12-12 18:42 UTC, Vyrastas approved these changes

2023-12-12 19:43 UTC, abtink approved these changes
Thanks. 👍

2023-12-12 20:22 UTC, jwhui commented on include/openthread/border_routing.h
> +    uint32_t mNumPlatformRaReceived;   ///< The number of platform generated RA handled by ProcessPlatformGeneratedRa.
Need to increment `OPENTHREAD_API_VERSION`

2023-12-13 20:18 UTC, jwhui approved these changes

2023-12-13 20:18 UTC, merged